version: '3'

services:

  pandora-mysql:
    image: mariadb
    container_name: pandora-mysql
    hostname: pandora-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd#1
      MYSQL_DATABASE: pandora
      MYSQL_USER: pandora
      MYSQL_PASSWORD: P@nd0r@
    ports:
      - 3306:3306
    volumes:
      - /srv/docker-data/pandora/mysql:/var/lib/mysql
    networks:
      ipaddr:
        ipv4_address: 172.17.1.1

  pandora-server:
    image: cent7-pandorafms-server:7.0NG.732-1
    container_name: pandora-server
    hostname: pandora-server
    restart: always
    environment:
      PANDORA_DB_HOST: pandora-mysql
      PANDORA_DB_NAME: pandora
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: P@nd0r@
    ports:
      - 41121:41121
    depends_on:
      - pandora-mysql
    networks:
      ipaddr:
        ipv4_address: 172.17.1.2

  pandora-console:
    image: cent7-pandorafms-console:7.0NG.732-1
    container_name: pandora-console
    hostname: pandora-console
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8022:8022
      - 8023:8023
    environment:
      PANDORA_DB_HOST: pandora-mysql
      PANDORA_DB_NAME: pandora
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: P@nd0r@
    depends_on:
      - pandora-mysql
    networks:
      ipaddr:
        ipv4_address: 172.17.1.3
    
networks:
  ipaddr:
    external:
      name: docker1
